# Generated by Django 4.2.1 on 2023-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_device_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
